#!/usr/bin/env bash
set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}"
echo "========================================"
echo "        Yaci Explorer Setup"
echo "========================================"
echo -e "${NC}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
cd "$PROJECT_ROOT"

# Check for .env file
if [[ ! -f .env ]]; then
  echo -e "${YELLOW}No .env file found. Creating from template...${NC}"
  cp .env.example .env
  echo -e "${GREEN}Created .env file${NC}"
fi

source .env 2>/dev/null || true

prompt() {
  local var_name=$1
  local prompt_text=$2
  local default_value=$3
  local current_value="${!var_name}"

  [[ -n "$current_value" ]] && default_value="$current_value"

  echo -ne "${BLUE}$prompt_text${NC}"
  [[ -n "$default_value" ]] && echo -ne " [${default_value}]: " || echo -ne ": "

  read -r input
  [[ -z "$input" ]] && input="$default_value"
  eval "$var_name='$input'"
}

echo ""
echo -e "${YELLOW}Select deployment type:${NC}"
echo "  1) Docker Compose (recommended)"
echo "  2) Native (systemd services)"
echo "  3) Frontend only (PostgREST already running)"
echo ""
read -p "Choice [1]: " deploy_type
deploy_type=${deploy_type:-1}

echo ""
echo -e "${YELLOW}Configuration:${NC}"

if [[ "$deploy_type" != "3" ]]; then
  prompt CHAIN_GRPC_ENDPOINT "Chain gRPC endpoint" "localhost:9090"
  prompt POSTGRES_PASSWORD "PostgreSQL password" "changeme"
fi

if [[ "$deploy_type" == "3" ]]; then
  prompt API_URL "PostgREST API URL" "http://localhost:3000"
  prompt CHAIN_REST_ENDPOINT "Chain REST endpoint (optional)" ""
fi

echo ""
read -p "Configure advanced options? [y/N]: " advanced
if [[ "$advanced" =~ ^[Yy]$ ]]; then
  prompt POSTGRES_USER "PostgreSQL user" "postgres"
  prompt POSTGRES_DB "PostgreSQL database" "yaci"
  prompt YACI_MAX_CONCURRENCY "Yaci max concurrency" "100"
fi

echo ""
echo -e "${YELLOW}Saving configuration...${NC}"

cat > .env << EOF
# Yaci Explorer Configuration
# Generated by setup.sh on $(date)

CHAIN_GRPC_ENDPOINT=${CHAIN_GRPC_ENDPOINT:-localhost:9090}
POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changeme}
POSTGRES_USER=${POSTGRES_USER:-postgres}
POSTGRES_DB=${POSTGRES_DB:-yaci}
EOF

[[ -n "${YACI_MAX_CONCURRENCY:-}" ]] && echo "YACI_MAX_CONCURRENCY=$YACI_MAX_CONCURRENCY" >> .env

echo -e "${GREEN}Configuration saved to .env${NC}"

# Create config.json for frontend-only deployment
if [[ "$deploy_type" == "3" ]]; then
  echo -e "${YELLOW}Creating frontend config.json...${NC}"
  cat > public/config.json << EOF
{
  "apiUrl": "${API_URL}",
  "chainRestEndpoint": "${CHAIN_REST_ENDPOINT:-}",
  "evmEnabled": true,
  "ibcEnabled": true,
  "appName": "Block Explorer"
}
EOF
  echo -e "${GREEN}Frontend configuration saved to public/config.json${NC}"
fi

echo ""
case $deploy_type in
  1)
    echo -e "${YELLOW}Starting Docker Compose deployment...${NC}"

    if ! command -v docker &> /dev/null; then
      echo -e "${RED}Error: Docker is not installed${NC}"
      exit 1
    fi

    cd docker
    docker compose up -d --build

    echo ""
    echo -e "${GREEN}Deployment complete!${NC}"
    echo ""
    echo "Services:"
    echo "  - Explorer UI:  http://localhost:3001"
    echo "  - PostgREST:    http://localhost:3000"
    echo "  - Prometheus:   http://localhost:2112/metrics"
    echo ""
    echo "Commands:"
    echo "  View logs:      docker compose -f docker/docker-compose.yml logs -f"
    echo "  Stop:           docker compose -f docker/docker-compose.yml down"
    ;;

  2)
    echo -e "${YELLOW}Starting native deployment...${NC}"

    if [[ "$EUID" -ne 0 ]]; then
      echo -e "${RED}Native deployment requires root. Run with sudo.${NC}"
      exit 1
    fi

    # Install PostgreSQL
    echo -e "${BLUE}Installing PostgreSQL...${NC}"
    apt-get update -qq
    apt-get install -y -qq postgresql postgresql-contrib

    sudo -u postgres psql -c "ALTER USER postgres PASSWORD '${POSTGRES_PASSWORD}';" 2>/dev/null || true
    sudo -u postgres createdb "${POSTGRES_DB}" 2>/dev/null || true

    # Install PostgREST
    echo -e "${BLUE}Installing PostgREST...${NC}"
    POSTGREST_VERSION="v12.0.2"
    wget -q "https://github.com/PostgREST/postgrest/releases/download/${POSTGREST_VERSION}/postgrest-${POSTGREST_VERSION}-linux-static-x86_64.tar.xz" -O /tmp/postgrest.tar.xz
    tar -xf /tmp/postgrest.tar.xz -C /usr/local/bin
    chmod +x /usr/local/bin/postgrest

    cat > /etc/postgrest.conf << EOF
db-uri = "postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB:-yaci}"
db-schema = "api"
db-anon-role = "web_anon"
server-port = 3000
EOF

    cat > /etc/systemd/system/postgrest.service << EOF
[Unit]
Description=PostgREST API Server
After=postgresql.service
Requires=postgresql.service

[Service]
ExecStart=/usr/local/bin/postgrest /etc/postgrest.conf
Restart=always

[Install]
WantedBy=multi-user.target
EOF

    # Install Go and Yaci
    echo -e "${BLUE}Installing Yaci indexer...${NC}"
    if ! command -v go &> /dev/null; then
      wget -q "https://go.dev/dl/go1.21.5.linux-amd64.tar.gz" -O /tmp/go.tar.gz
      tar -C /usr/local -xzf /tmp/go.tar.gz
      export PATH=$PATH:/usr/local/go/bin
    fi

    go install github.com/cordtus/yaci@latest || {
      git clone https://github.com/cordtus/yaci /tmp/yaci
      cd /tmp/yaci && go build -o /usr/local/bin/yaci .
      cd "$PROJECT_ROOT"
    }

    cat > /etc/systemd/system/yaci.service << EOF
[Unit]
Description=Yaci Blockchain Indexer
After=postgresql.service
Requires=postgresql.service

[Service]
ExecStart=/usr/local/bin/yaci extract postgres ${CHAIN_GRPC_ENDPOINT} -p postgres://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB:-yaci} --live -k --enable-prometheus --prometheus-addr 0.0.0.0:2112
Restart=always

[Install]
WantedBy=multi-user.target
EOF

    # Install Bun and build frontend
    echo -e "${BLUE}Building frontend...${NC}"
    if ! command -v bun &> /dev/null; then
      curl -fsSL https://bun.sh/install | bash
      export PATH="$HOME/.bun/bin:$PATH"
    fi

    bun install
    bun run build

    cat > /etc/systemd/system/yaci-explorer.service << EOF
[Unit]
Description=Yaci Explorer Frontend
After=postgrest.service

[Service]
WorkingDirectory=${PROJECT_ROOT}
ExecStart=$(which bun) serve ./dist
Restart=always

[Install]
WantedBy=multi-user.target
EOF

    systemctl daemon-reload
    systemctl enable postgresql postgrest yaci yaci-explorer
    systemctl start postgresql postgrest yaci yaci-explorer

    echo ""
    echo -e "${GREEN}Deployment complete!${NC}"
    echo ""
    echo "Services:"
    echo "  - Explorer UI:  http://localhost:3001"
    echo "  - PostgREST:    http://localhost:3000"
    echo ""
    echo "Commands:"
    echo "  View status:    systemctl status yaci postgrest yaci-explorer"
    echo "  View logs:      journalctl -u yaci -f"
    ;;

  3)
    echo -e "${YELLOW}Building frontend only...${NC}"

    if ! command -v bun &> /dev/null; then
      echo -e "${RED}Error: bun is not installed. Install from https://bun.sh${NC}"
      exit 1
    fi

    bun install
    bun run build

    echo ""
    echo -e "${GREEN}Build complete!${NC}"
    echo ""
    echo "Configuration: public/config.json has been created"
    echo ""
    echo "To run locally:"
    echo "  bun serve ./dist"
    echo ""
    echo "For production:"
    echo "  1. Copy dist/ to your web server"
    echo "  2. Ensure config.json is accessible at /config.json"
    ;;

  *)
    echo -e "${RED}Invalid option${NC}"
    exit 1
    ;;
esac
